#
# Travis CI configuration file
#

dist: trusty
language: csharp
dotnet: 2.0.0
sudo: required

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
 - dotnet restore

solution: NLibuv.sln

script:
  - dotnet test test/NLibuv.Tests/NLibuv.Tests.csproj
